stages:
    - build

build:
    stage: build
#    image: 10.250.30.67:5000/kwagent
    image: ladlestein/kwagent
    script:
        - kwinject gcc foo.c -o nothing
        - kwbuildproject --url http://localhost:8190/projectile -o kwtables kwinject.out
        - kwadmin load --url http://localhost:8190 projectile kwtables
