stages:
    - analyze

base analysis:
    stage: analyze
    only: 
        - master
    image: ladlestein/kwagent
    script:
        - kwinject sh -c "gcc foo.c -o nothing"
        - kwbuildproject --url http://$KLOCWORK_SERVER_HOST:$KLOCWORK_SERVER_PORT/projectile -o kwtables kwinject.out
        - kwadmin load --url http://$KLOCWORK_SERVER_HOST:$KLOCWORK_SERVER_PORT projectile kwtables

differential analysis:
    stage: analyze
    except:
        - master
    image: ladlestein/kwagent
    script: 
        - kwinject sh -c "gcc foo.c -o nothing"
        - kwadmin --url http://$KLOCWORK_SERVER_HOST:$KLOCWORK_SERVER_PORT/projectile list-builds projectile